#server:
#  port: 8443
#  ssl:
#    key-store: classpath:ssl/mykeys.jks
#    key-store-password: pengpeng
#    key-password: pengpeng

spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taco_cloud?serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

taco:
  orders:
    pageSize: 20


